### ISSUE TITLE
Update documentations

### ISSUE THREAD

**Issue by deniss-eh** [deniss-eh/DSA#2]
update documentations according to hacktoberfest.
documentation includes files like README.md , CODE_OF_CONDUCT.md , CONTRIBUTING.md , etc.
make sure to add this issue link to your pull request when opening a pull request for this issue

**Comment by Chandak-Keshav** [comment]
Kindly assign me this @deniss-eh

**Comment by amanaggarwal06** [comment]
Hey,I wanted to do this.
Can you explain what I have to do?

**Comment by deniss-eh** [comment]
> Kindly assign me this @deniss-eh

sure brah!

**Comment by deniss-eh** [comment]
> Hey,I wanted to do this. Can you explain what I have to do?

you just need to add or update documentations as you can read the description.
