### ISSUE TITLE
Add programs related to DSA problems

### ISSUE THREAD

**Issue by deniss-eh** [deniss-eh/DSA#3]

**Comment by b1form** [comment]
I want to contribute for python programs.

**Comment by blieve16** [comment]
Please check PR #5

**Comment by b1form** [comment]
Please check PR #6

**Comment by SamagraAg** [comment]
@deniss-eh check my PR. I have added a DSA problem in python.

**Comment by saishubham468** [comment]
Hi @deniss-eh i would like to contribute to this issue.

**Comment by vaibhv232** [comment]
please check pr #10

**Comment by deniss-eh** [comment]
> I want to contribute for python programs.

ya sure! you can

**Comment by deniss-eh** [comment]
> Hi @deniss-eh i would like to contribute to this issue.

sure

**Comment by deniss-eh** [comment]
all valid prs are merged!
